name: DailyShop
author: EricL (Ericdebouwer)
main: com.ericdebouwer.dailyshop.DailyShop
api-version: 1.13
version: 1.0
description: Customizable shop with daily items!
depend: [Vault]
commands:
   dailyshop:
      description: Main command
      aliases: [ds]
   dsa:
      description: Daily Shop admin command
      
permissions:
    dailyshop.admin:
       description: allows you to add items to the shop
       default: op